mode: "dev" # dev, prod

log:
  level: "debug"
  format: "json"
  output: "stdout"

user:
  http:
    port: 9001
    host: "0.0.0.0"
    read_timeout: 10
    write_timeout: 10
    idle_timeout: 10
    max_header_bytes: 1024
  storage:
    driver: "sqlite"
    mysql:
      host: "localhost"
      port: 3306
      user: "root"
      password: "123456"
      db: "monica"
    sqlite:
      path: "monica.db"
  jwt:
    secret: "monica"
