// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/3c4j/monica/lib/storage"
	"github.com/3c4j/monica/monica"
	"github.com/3c4j/monica/pkg/logger"
	"github.com/3c4j/monica/user/config"
	"github.com/3c4j/monica/user/entity"
	"github.com/3c4j/monica/user/handler"
	"github.com/3c4j/monica/user/service"
)

// Injectors from wire.go:

func InitModule(lg *logger.Logger) (monica.Module, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	storageConfig := config.NewStorageConfig(configConfig)
	db, err := storage.NewStorage(storageConfig)
	if err != nil {
		return nil, err
	}
	repository := entity.NewUserRepository(db, lg)
	authService := service.NewAuthService(repository, lg)
	jwtService := service.NewJwtService(configConfig, lg)
	authHandler := handler.NewAuthHandler(authService, jwtService, lg)
	module, err := NewModule(lg, configConfig, authHandler)
	if err != nil {
		return nil, err
	}
	return module, nil
}
